title: "Cloud Cafes"
description: "Technical documentation and blog" 
baseurl: ""
url: "https://cloudcafes.github.io"

# Colors similar to your WordPress theme
accent_color: "#21759b"  # Your blue color
background_color: "#ffffff"

# Header configuration
header_pages:
  - about.md
  - index.md

# Social links (like your WordPress)
social:
  github: cloudcafes
  # Add others as needed