title: "Cloud Cafes"
description: "Technical documentation and blog" 
baseurl: ""
url: "https://cloudcafes.github.io"

# NO theme configuration - we're using local files
markdown: kramdown
highlighter: rouge
permalink: pretty

# Your settings
github_edit: "https://github.com/cloudcafes/cloudcafes.github.io/edit/main/"
search: true
output: web

# GitHub Pages plugins (supported)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed