title: "Cloud Cafes"
description: "Technical documentation and blog"
baseurl: ""  # Leave empty for username.github.io
url: "https://cloudcafes.github.io" 

# Theme settings
theme: "jekyll-theme-documentation"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Documentation theme specific
github_edit: "https://github.com/cloudcafes/cloudcafes.github.io/edit/main/"
search: true
output: web